apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
    group: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        group: frontend
    spec:
      serviceAccountName: github-actions
      automountServiceAccountToken: false
      containers:
        - name: test-app
          image: ghcr.io/vendory-dev/test:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
